### ISSUE TITLE
[Feature Request] Support multiple targets and patterns

### ISSUE THREAD

**Issue by KallenW** [TENX-S/dir_watcher#6]
The signature of the constructor of `DirWatcher` may look like below:
```rust
pub fn new(targets: &[&str], patterns: &[&str]) -> Self  { ... }
```

**Comment by TENX-S** [comment]
When there are many different targets and patterns, how to determine the relationship between them ? For every target in `targets`, do we need to find out all of the patterns ?

**Comment by KallenW** [comment]
This signature below looks fair enough
`binding = &[(target, &[pattern])]`
```rust
pub fn new(binding: &[(&str, &[&str])]) -> Self  { ... }
```
Or we can expose a new method, like:
`binding = &[target, &[pattern]]`
```rust
pub fn add_target(binding: (&str, &[&str]))
```

**Comment by TENX-S** [comment]
The release 0.3.0 shows a preview of your idea. @KallenW
